---
title: "Some things I learned this quarter"
subtitle: "FISH 497"
author: "Jenna Morris" 
date: "jemorris@uw.edu"
output: ioslides_presentation
---
# Introduction

## About me | Personal

- Born & raised in Boise, Idaho
- Curry and falafel enthusiast
- Lover of (not small) dogs & sloths

## About me | Academic

- B.S. Whitworth University, Spokane, WA
- Major: Biology & Environmental Studies

## About me | Things I've missed during the pandemic

1. In-person celebration of milestones (e.g., graduation, thesis defense, passing exams, birthdays)
2. Spending the winter holidays with loved ones
3. Working on campus (despite Bloedel Hall's flaws)

# Data science

## Course topics | 3 things I enjoyed learning about

1. The power and potential of GitHub
2. Best practices for reproducibility (e.g., Tidy data, metadata, compendia)
3. Considerations for accessibility, equity, communication, and ethics

## Course topics | 3 things I'd like to learn more about

1. Data science in action - really enjoyed the guest lectures!
2. Building infrastructure for peer code review at lab and/or department levels
3. Developing data management plans

## {data-background=NorsePeakFire.jpg data-background-size=cover}